import type { DisplaySectionProduct } from './DisplaySectionList';

/**
 * 퍼블리싱용 더미 데이터 — Figma "HomeScreen" 3개 진열 섹션(node 577:20681,
 * 577:20688, 577:20695) 실측 그대로. 데이터 연동 시 `hooks/home` 훅이 대체한다
 * (structure-convention §6-2, API 스펙 미확정).
 */
export type MockDisplaySection = {
  id: string;
  title: string;
  subtitle: string;
  href: string;
  products: DisplaySectionProduct[];
};

export const MOCK_DISPLAY_SECTIONS: MockDisplaySection[] = [
  {
    id: 'hot-deals',
    title: '🛒 지금 가장 많이 담는 특가',
    subtitle: '꼭 담아야 할 추천 특가템 최대 50%  OFF',
    href: '/products?section=hot-deals',
    products: [
      {
        id: 'p1',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[연세우유 x 마켓컬리] 전용목장우유 900mL',
        originalPriceLabel: '3,400',
        discountLabel: '25%',
        priceLabel: '2,780원~',
        reviewCountLabel: '9,999+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p2',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[도연하다] 스지 된장찌개',
        originalPriceLabel: '7,900',
        discountLabel: '32%',
        priceLabel: '5,372원~',
        reviewCountLabel: '9,999+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p3',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[스미후루] 감숙왕 바나나 2종',
        originalPriceLabel: '4,500',
        discountLabel: '15%',
        priceLabel: '3,825원~',
        reviewCountLabel: '5,000+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p4',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[우리쌀 왕호두] 호두과자 (30g X 10개)',
        originalPriceLabel: '9,000',
        discountLabel: '20%',
        priceLabel: '7,200원~',
        reviewCountLabel: '2,500+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
    ],
  },
  {
    id: 'grand-view-cafe',
    title: '🛒 1년에 단 4번, 그랜드뷰컬페',
    subtitle: '100% 당첨 랜덤쿠폰부터 99% 래플까지',
    href: '/products?section=grand-view-cafe',
    products: [
      {
        id: 'p5',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[선물세트] 태우한우 1+ 실속 구이 세트 (냉동)',
        originalPriceLabel: '217,000',
        discountLabel: '33%',
        priceLabel: '145,000원~',
        reviewCountLabel: '9,999+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p6',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[오리온] 초코송이 36g x 18입',
        originalPriceLabel: '10,800',
        discountLabel: '7%',
        priceLabel: '10,040원~',
        reviewCountLabel: '9,999+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p7',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[KF365] 브로콜리 1입 (250g)',
        originalPriceLabel: '4,990',
        discountLabel: '14%',
        priceLabel: '4,290원~',
        reviewCountLabel: '5,000+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p8',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[포비베이글] 듬뿍 무화과 잼 140g',
        originalPriceLabel: '7,000',
        discountLabel: '10%',
        priceLabel: '6,300원~',
        reviewCountLabel: '2,500+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
    ],
  },
  {
    id: 'chuseok-prep',
    title: '🎁 눈 깜짝하면 다가올 추석 준비!',
    subtitle: '최대 혜택으로 선물하세요! 쿠폰+최대 77% OFF',
    href: '/products?section=chuseok-prep',
    products: [
      {
        id: 'p9',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[일상식탁] 부산식 얼큰 낙곱새',
        originalPriceLabel: '18,900',
        discountLabel: '13%',
        priceLabel: '16,443원~',
        reviewCountLabel: '9,999+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p10',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[사리원] 소불고기 전골',
        originalPriceLabel: '15,900',
        discountLabel: '15%',
        priceLabel: '13,515원~',
        reviewCountLabel: '9,999+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p11',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: '[동원] 야채참치 150g',
        originalPriceLabel: '3,680',
        discountLabel: '13%',
        priceLabel: '3,180원~',
        reviewCountLabel: '5,000+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
      {
        id: 'p12',
        imageAlt: '',
        deliveryLabel: '샛별배송',
        name: "[Kurly's] 국산콩 두부 3종 (택1)",
        originalPriceLabel: '2,880',
        discountLabel: '10%',
        priceLabel: '1,440원~',
        reviewCountLabel: '2,500+',
        couponPercentLabel: '+25%',
        kurlyOnly: true,
      },
    ],
  },
];
