import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { svgFileToJsx, renderFnCode } from './svg-to-tsx.mjs';

const SVG_DIR = path.resolve('src/components/atoms/TabIcon/svg');
const OUT = path.resolve('src/components/atoms/TabIcon/tab-icons.generated.tsx');

const files = readdirSync(SVG_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const byName = new Map();
const fnCodes = [];

for (const file of files) {
  const base = path.basename(file, '.svg');
  const match = base.match(/^(.+)-(default|active)$/);
  if (!match) {
    console.warn(`이름 규칙 불일치, 건너뜀: ${file}`);
    continue;
  }
  const [, name, state] = match;
  const jsx = await svgFileToJsx(path.join(SVG_DIR, file));
  // TabIcon 전용 색 치환: HEX_TO_VAR 는 고정 프리미티브(--color-black/--color-brand-500)로만
  // 매핑하는데, 탭 아이콘은 default/active 각각 Text/Primary·Brand/Primary 시맨틱 의미라
  // 다크모드에서 값이 갈라져야 한다(마이컬리 BottomNav 다크 지원, 2026-09-18) — 이 빌드에서만
  // 시맨틱 토큰으로 한 번 더 치환한다(다른 아이콘 세트의 HEX_TO_VAR 동작에는 영향 없음).
  //
  // `--color-fg`/`--color-primary`(별칭, `@theme inline`)가 아니라 `--fg`/`--primary`
  // (프리미티브)를 직접 참조한다 — Tailwind 클래스(`text-fg` 등)는 별칭을 프리미티브로
  // "inline" 해서 생성되지만, SVG `fill="var(--color-fg)"`처럼 raw CSS var 로 직접 쓰면
  // 그 inline 최적화를 안 타서 `[data-theme='dark']` 로컬 오버라이드를 못 따라가고 루트
  // (라이트) 값에 고정돼 버린다 — 다크모드에서 탭 아이콘이 계속 검게 보이던 버그의 원인
  // (BottomNav 다크 QA, 2026-09-22). 프리미티브는 이 간접 단계가 없어 정상 캐스케이드된다.
  jsx.inner = jsx.inner
    .replace(/var\(--color-black\)/g, 'var(--fg)')
    .replace(/var\(--color-brand-500\)/g, 'var(--primary)');
  const fnName = `render_tab_${name}_${state}`;
  fnCodes.push(renderFnCode(fnName, jsx));
  if (!byName.has(name)) byName.set(name, {});
  byName.get(name)[state] = { viewBox: jsx.viewBox, fnName };
}

const names = [...byName.keys()].sort();
const unionBody = names.map((n) => `'${n}'`).join(' | ');

const registryEntries = names
  .map((name) => {
    const d = byName.get(name);
    return `  ${name}: {
    default: { viewBox: '${d.default.viewBox}', render: (idFor) => ${d.default.fnName}(idFor) },
    active: { viewBox: '${d.active.viewBox}', render: (idFor) => ${d.active.fnName}(idFor) },
  },`;
  })
  .join('\n');

const out = `// AUTO-GENERATED by scripts/icons (svgr 기반) — do not hand-edit.
// 소스: src/components/atoms/TabIcon/svg/*.svg (Figma "TabBar_Icon" 컴포넌트셋, issue #11).
// 재생성: npm run icons:build
import type { ReactNode } from 'react';

export type TabName = ${unionBody};

type TabIconVariant = {
  viewBox: string;
  render: (idFor: (raw: string) => string) => ReactNode;
};

${fnCodes.join('\n\n')}

export const TAB_ICONS: Record<TabName, { default: TabIconVariant; active: TabIconVariant }> = {
${registryEntries}
};
`;

writeFileSync(OUT, out);
console.log(`TabIcon: ${names.length}개 탭 -> ${OUT}`);
