import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { svgFileToJsx, renderFnCode } from './svg-to-tsx.mjs';

const SVG_DIR = path.resolve('src/components/atoms/Icon/svg');
const OUT = path.resolve('src/components/atoms/Icon/icons.generated.tsx');

const files = readdirSync(SVG_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const byName = new Map();
const fnCodes = [];

for (const file of files) {
  const base = path.basename(file, '.svg');
  const match = base.match(/^(.+)-(\d+)$/);
  if (!match) {
    console.warn(`이름 규칙 불일치, 건너뜀: ${file}`);
    continue;
  }
  const [, name, size] = match;
  const jsx = await svgFileToJsx(path.join(SVG_DIR, file));
  const fnName = `render_${name.replace(/-/g, '_')}_${size}`;
  fnCodes.push(renderFnCode(fnName, jsx));
  if (!byName.has(name)) byName.set(name, []);
  byName.get(name).push({ viewBox: jsx.viewBox, themable: jsx.themable, fnName });
}

const names = [...byName.keys()].sort();
const unionBody = names.map((n) => `  | '${n}'`).join('\n');

const registryEntries = names
  .map((name) => {
    const keyLiteral = /^[a-zA-Z_$][\w$]*$/.test(name) ? name : `'${name}'`;
    const variants = byName
      .get(name)
      .map(
        (v) =>
          `    { viewBox: '${v.viewBox}', themable: ${v.themable}, render: (idFor) => ${v.fnName}(idFor) },`,
      )
      .join('\n');
    return `  ${keyLiteral}: [\n${variants}\n  ],`;
  })
  .join('\n');

const out = `// AUTO-GENERATED by scripts/icons (svgr 기반) — do not hand-edit.
// 소스: src/components/atoms/Icon/svg/*.svg (Figma "Icon" 그룹, issue #11).
// 재생성: npm run icons:build (svg/ 에 파일 추가·수정 후 재실행)
import type { ReactNode } from 'react';

export type IconName =
${unionBody};

type IconVariant = {
  viewBox: string;
  themable: boolean;
  render: (idFor: (raw: string) => string) => ReactNode;
};

${fnCodes.join('\n\n')}

export const ICONS: Record<IconName, IconVariant[]> = {
${registryEntries}
};
`;

writeFileSync(OUT, out);
console.log(`Icon: ${names.length}개 이름, ${files.length}개 variant -> ${OUT}`);
