import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { svgFileToJsx, renderFnCode } from './svg-to-tsx.mjs';

const SVG_DIR = path.resolve('src/components/atoms/Logo/svg');
const OUT = path.resolve('src/components/atoms/Logo/logos.generated.tsx');

const files = readdirSync(SVG_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const entries = [];
const fnCodes = [];

for (const file of files) {
  const name = path.basename(file, '.svg');
  const jsx = await svgFileToJsx(path.join(SVG_DIR, file));
  const fnName = `render_${name.replace(/-/g, '_')}`;
  fnCodes.push(renderFnCode(fnName, jsx));
  const parts = jsx.viewBox
    .trim()
    .split(/[\s,]+/)
    .map(Number);
  const [, , vw, vh] = parts;
  if (parts.length !== 4 || !Number.isFinite(vw) || !Number.isFinite(vh) || vw <= 0 || vh <= 0) {
    throw new Error(
      `잘못된 viewBox "${jsx.viewBox}" (${file}) — width/height 가 유한한 양수가 아님`,
    );
  }
  entries.push({ name, viewBox: jsx.viewBox, aspectRatio: `${vw} / ${vh}`, fnName });
}

entries.sort((a, b) => a.name.localeCompare(b.name));
const unionBody = entries.map((e) => `'${e.name}'`).join(' | ');

const registryEntries = entries
  .map((e) => {
    const keyLiteral = /^[a-zA-Z_$][\w$]*$/.test(e.name) ? e.name : `'${e.name}'`;
    return `  ${keyLiteral}: { viewBox: '${e.viewBox}', aspectRatio: ${e.aspectRatio}, render: (idFor) => ${e.fnName}(idFor) },`;
  })
  .join('\n');

const out = `// AUTO-GENERATED by scripts/icons (svgr 기반) — do not hand-edit.
// 소스: src/components/atoms/Logo/svg/*.svg (Figma "Logo" 그룹, issue #11).
// 재생성: npm run icons:build
import type { ReactNode } from 'react';

export type LogoName = ${unionBody};

type LogoDef = {
  viewBox: string;
  /** 원본 가로:세로 비율 (intrinsic width / intrinsic height) */
  aspectRatio: number;
  render: (idFor: (raw: string) => string) => ReactNode;
};

${fnCodes.join('\n\n')}

export const LOGOS: Record<LogoName, LogoDef> = {
${registryEntries}
};
`;

writeFileSync(OUT, out);
console.log(`Logo: ${entries.length}개 -> ${OUT}`);
