import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { svgFileToJsx, renderFnCode } from './svg-to-tsx.mjs';

const SVG_DIR = path.resolve('src/components/atoms/TabIcon/svg');
const OUT = path.resolve('src/components/atoms/TabIcon/tab-icons.generated.tsx');

const files = readdirSync(SVG_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const byName = new Map();
const fnCodes = [];

for (const file of files) {
  const base = path.basename(file, '.svg');
  const match = base.match(/^(.+)-(default|active)$/);
  if (!match) {
    console.warn(`이름 규칙 불일치, 건너뜀: ${file}`);
    continue;
  }
  const [, name, state] = match;
  const jsx = await svgFileToJsx(path.join(SVG_DIR, file));
  const fnName = `render_tab_${name}_${state}`;
  fnCodes.push(renderFnCode(fnName, jsx));
  if (!byName.has(name)) byName.set(name, {});
  byName.get(name)[state] = { viewBox: jsx.viewBox, fnName };
}

const names = [...byName.keys()].sort();
const unionBody = names.map((n) => `'${n}'`).join(' | ');

const registryEntries = names
  .map((name) => {
    const d = byName.get(name);
    return `  ${name}: {
    default: { viewBox: '${d.default.viewBox}', render: (idFor) => ${d.default.fnName}(idFor) },
    active: { viewBox: '${d.active.viewBox}', render: (idFor) => ${d.active.fnName}(idFor) },
  },`;
  })
  .join('\n');

const out = `// AUTO-GENERATED by scripts/icons (svgr 기반) — do not hand-edit.
// 소스: src/components/atoms/TabIcon/svg/*.svg (Figma "TabBar_Icon" 컴포넌트셋, issue #11).
// 재생성: npm run icons:build
import type { ReactNode } from 'react';

export type TabName = ${unionBody};

type TabIconVariant = {
  viewBox: string;
  render: (idFor: (raw: string) => string) => ReactNode;
};

${fnCodes.join('\n\n')}

export const TAB_ICONS: Record<TabName, { default: TabIconVariant; active: TabIconVariant }> = {
${registryEntries}
};
`;

writeFileSync(OUT, out);
console.log(`TabIcon: ${names.length}개 탭 -> ${OUT}`);
