// AUTO-GENERATED by scripts in scratchpad/icon-gen — do not hand-edit.
// Source: Figma "Icon_Arrow" component set export (issue #11).
import type { ReactNode } from 'react';

export type CarouselArrowVariant = 'outline' | 'filled';
export type CarouselArrowDirection = 'left' | 'right';

type Def = {
  viewBox: string;
  render: (idFor: (raw: string) => string) => ReactNode;
};

function render_outline_left(_idFor: (raw: string) => string): ReactNode {
  return (
    <>
      <rect x="2.5" y="2.5" width="35" height="35" rx="17.5" stroke="#DDE4ED" />
      <path
        d="M21.9999 15.5L18.0001 20L21.9999 24.5"
        stroke="#DDE4ED"
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
    </>
  );
}

function render_outline_right(_idFor: (raw: string) => string): ReactNode {
  return (
    <>
      <rect
        x="37.4996"
        y="37.5"
        width="35"
        height="35"
        rx="17.5"
        transform="rotate(180 37.4996 37.5)"
        stroke="#DDE4ED"
      />
      <path
        d="M17.9997 24.5L21.9995 20L17.9997 15.5"
        stroke="#DDE4ED"
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
    </>
  );
}

function render_filled_left(_idFor: (raw: string) => string): ReactNode {
  return (
    <>
      <rect x="2" y="2" width="32" height="32" rx="16" fill="white" />
      <rect x="2" y="2" width="32" height="32" rx="16" stroke="#E2E2E2" />
      <path
        d="M21.3977 12.3977L15.7954 18L21.3977 23.6023L20.6023 24.3977L14.6023 18.3977C14.3826 18.178 14.3826 17.822 14.6023 17.6023L20.6023 11.6023L21.3977 12.3977Z"
        fill="#101010"
      />
    </>
  );
}

function render_filled_right(_idFor: (raw: string) => string): ReactNode {
  return (
    <>
      <rect x="2" y="2" width="32" height="32" rx="16" fill="white" />
      <rect x="2" y="2" width="32" height="32" rx="16" stroke="#E2E2E2" />
      <path
        d="M14.4375 23.6016L20.0398 17.9993L14.4375 12.397L15.2329 11.6016L21.2329 17.6016C21.4526 17.8212 21.4526 18.1773 21.2329 18.397L15.2329 24.397L14.4375 23.6016Z"
        fill="#101010"
      />
    </>
  );
}

export const CAROUSEL_ARROWS: Record<CarouselArrowVariant, Record<CarouselArrowDirection, Def>> = {
  outline: {
    left: { viewBox: '0 0 40 40', render: (idFor) => render_outline_left(idFor) },
    right: { viewBox: '0 0 40 40', render: (idFor) => render_outline_right(idFor) },
  },
  filled: {
    left: { viewBox: '0 0 36 36', render: (idFor) => render_filled_left(idFor) },
    right: { viewBox: '0 0 36 36', render: (idFor) => render_filled_right(idFor) },
  },
};
